export const ADD_TRANSACTION = 'ADD_TRANSACTION';
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION';
export const REMOVE_TRANSACTION = 'REMOVE_TRANSACTION';
export const FILTER_TRANSACTIONS = 'FILTER_TRANSACTIONS';
export const UPDATE_TRANSACTION_ID = 'UPDATE_TRANSACTION_ID';
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';


export const FETCH_BUDGET = 'FETCH_BUDGET';
export const FETCH_BUDGETS = 'FETCH_BUDGETS';
export const ADD_BUDGET = 'ADD_BUDGET';
export const UPDATE_BUDGET_ID = 'UPDATE_BUDGET_ID';
export const UPDATE_BUDGET = 'UPDATE_BUDGET';
export const REMOVE_BUDGET = 'REMOVE_BUDGET';
export const SET_BUDGET_FOR_TRANS_VIEW = 'SET_BUDGET_FOR_TRANS_VIEW';

export const SHOW_FAILURE_MESSAGE = 'FAIL_MESSAGE';
export const SHOW_SUCCESS_MESSAGE = 'SUCCESS_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const SWITCH_VIEW = 'SWITCH_VIEW';

export const SET_ENTITY = 'SET_ENTITY';
export const CLEAR_ENTITY = 'CLEAR_ENTITY';

export const SET_MODE = 'SET_MODE';
export const CLEAR_MODE = 'CLEAR_MODE';
